### PR TITLE
Add cabal file in examples/ folder

### PR DESCRIPTION
**Pull request by sid-kap**
This allows you to use cabal to ensure that the examples at least typecheck with the code.

I'm not sure if this is what @bollu had in mind, but this does the job. Running `stack init` in the root directory of the project makes a `stack.yaml` file that contains the lines 

```
packages:
- '.'
- examples/
```

which means that every time you run `stack build`, both the `plots` package (in `.`) and the `plots-examples` package (in `examples/`) get built.

(Tangentially related: I've been getting compile errors of the following sort

```
    /home/sidharth/clones/plots/examples/bar.hs:6:8:                                  
        Could not find module ‘Plots.Themes’                                          
        Perhaps you meant                                                             
          Plots.Types (from plots-0.1.0.0@plots_HhETzYv8ixNLZISisq2okC)               
        Use -v to see a list of the files searched for. 
```

in many of the examples. Is this because the module has been removed or its name has been changed or something? If it's a simple fix, I'd be willing to modify the examples to make sure they all typecheck.)

By the way, this code looks really cool so far! I think it's a great idea to build a plots library directly on top of diagrams.

### CODE REVIEW

**Comment by cchalmers** [comment]
Thanks for looking at this. I agree I should be testing that examples at least type check. I don't want all the examples to be built whenever someone tries to build it with stack. Partly because some of the examples require additional packages. Also I don't really want to build the executables for all the examples, this would take a lot of disk space (probably gigabytes) when they can all by run with `runghc`.

I'd prefer if type checking the examples was part of the test suite but I'm not sure the best way to do this.

A lot of the examples no longer build because I changed large chunks of `plots` without updating the examples. I'll start working on them so they at least compile (or move/delete the ones that longer work)

**Comment by sid-kap** [comment]
Is there a `Plots.Themes` module that is accidentally not in version control? I was trying to play with the examples but almost all of them depended on this module, which seems to not exist.

**Comment by sid-kap** [comment]
Ah, looks like it is called `Plots.Style` now. Hopefully the examples will work for me now!

**Comment by cchalmers** [comment]
Yeah, that was one of the changes but there were more. I've just pushed fixes for most of the examples. There are some I couldn't fix that I've moved to the `old` directory.

**Comment by sid-kap** [comment]
Awesome, thanks!

**Pull request closed without merging**
