### PR TITLE
Update README with examples instructions

### PR DESCRIPTION
**Pull request by sid-kap**
I've updated the README with instructions on how to build the examples.

I know you gave me push access, but I feel more comfortable making PRs to make sure that everything looks good before pushing things to master.

### CODE REVIEW

**Comment by cchalmers** [comment]
I've removed the dataset module so you should just have to do `stack runghc test/RunExamples.hs`. 

Also, I'm considering moving `RunExamples.hs` to the the examples folder, since it's where I'd expect it to be. Any thoughts?

**Comment by sid-kap** [comment]
That seems fine with me. We should probably keep the following things in mind though:

1) When we do that, we should edit `RunExamples` to make sure it doesn't think that `examples/RunExamples.hs` is an image source file.
2) In the cabal file for examples, we would have to include `hs-source-files: <examples directory>` (I think). Would it be a bad thing to have these example source files in that directory? I'm worried that cabal might think that they are additional modules needed in order to build `RunExamples`, and thus might waste time compiling them. Do you know what cabal does in this case?

**Comment by sid-kap** [comment]
By the way, I just realized that now that the Dataset module is removed, we could put the cabal entry for the RunExamples executable in the main `plots` cabal file (and thus have only one cabal file), which would obviate (2) above.

**Comment by sid-kap** [comment]
Can we go ahead and merge this now, and then consider the other changes you mentioned after that?

**Comment by sid-kap** [comment]
Thanks!

**Pull request merged**
