### PR TITLE
Fix histogram example

### PR DESCRIPTION
**Pull request by sid-kap**
I wasn't sure what the old histogram example was doing (how do you make a histogram of a list of `(Double, Double)`?), but here's a working example that works with the current API.

### CODE REVIEW

**Comment by cchalmers** [comment]
Nice, thanks. I'm not about the last example was either, maybe a weighted histogram.

**Comment by sid-kap** [comment]
By the way, I'm not sure if you saw my other comment, but it appears that `functions.hs`, `points.hs`, `ratiobar.hs`, and `smoothsimple.hs` all import Plots.Themes, and thus they probably don't work. Should we move those to `examples/old` as well?

**Comment by cchalmers** [comment]
Ah yes, thanks. I've moved them.

**Comment by sid-kap** [comment]
Great, thanks!

**Pull request merged**
