### PR TITLE
support building with GHC-7.8 

### PR DESCRIPTION
**Pull request by bergey**
and other small changes.

### CODE REVIEW

**Comment by cchalmers** [comment]
Great, thanks. My spelling really is terrible :) I think using `forM` would be better than adding an `Applicative` constraint.

**Comment by bergey** [comment]
Sure, `forM` is fine.  Are there still `Monad`s somewhere that aren't `Applicative`? =)  Or you just don't like making the type signature longer?

**Comment by cchalmers** [comment]
Don't like long signatures. They're already long enough :)

**Comment by bergey** [comment]
Makes sense.

**Pull request merged**
